---
- hosts: workers
  become: true
  gather_facts: false
  tasks: 
    - name: Checking Git version
      shell: git --version
      register: mygit
    - name: Printing Git version
      debug:
        msg: "{{ mygit.stdout }}"
    - name: Read-write git checkout from github
      ansible.builtin.git:     
        repo: https://github.com/SAIKATDASGIT/argocd.git
        dest: /home/$USER/argo
    - name: Copying from Master
      copy:
         src: /home/runner/work/github-action/github-action/test
         dest: /home/ubuntu/
    - name: Copying Already file
      copy:
         src: /home/runner/work/github-action/github-action/already
         dest: /home/ubuntu/
- hosts: vm1
   become: true
   gather_facts: false
   tasks:
     - name: Copying File1 to vm1
       src: /home/runner/work/github-action/github-action/test/file1
       dest: /home/ubuntu
- hosts: vm2
    become: true
    gather_facts: false
    tasks:
      - name: Copying File2 vm2
        src: /home/runner/work/github-action/github-action/test/file2
        dest: /home/ubuntu
  
