---
- hosts: workers
  become: true
  gather_facts: false
  tasks: 
    - name: Checking Git version
      shell: git --version
      register: mygit
    - name: Printing Git version
      debug:
        msg: "{{ mygit.stdout }}"
    - name: Read-write git checkout from github
      ansible.builtin.git:     
        repo: https://github.com/SAIKATDASGIT/argocd.git
        dest: /home/$USER/argo
    - name: Copying from Master
      copy:
         src: /home/runner/work/github-action/github-action/test
         dest: /home/ubuntu/
    - name: Copying Already file
      copy:
         src: /home/runner/work/github-action/github-action/already
         dest: /home/ubuntu/
- hosts: vm1
  become: true
  gather_facts: false
  tasks:
    - name: Copying File1 to vm1
      copy:
        src: /home/runner/work/github-action/github-action/file1
        dest: /home/ubuntu
    - name: Copying Index file to VM1
      copy:
        src: /home/runner/work/github-action/github-action/vm1_nginx.html
        dest: var/www/html/index.nginx-debian.html
- hosts: vm2
  become: true
  gather_facts: false
  tasks:
    - name: Copying File2 to VM2
      copy:
        src: /home/runner/work/github-action/github-action/file2
        dest: /home/ubuntu
    - name: Copying Index File to VM2
      copy:
        src: /home/runner/work/github-action/github-action/vm2_nginx.html
        dest: var/www/html/index.nginx-debian.html
  
