
name: Ansible deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
    - name: set ansible config secrets
      env:
        KEY: ${{ secrets.PUBLIC_KEY }}
      run: |
        mkdir /home/runner/.ssh
        echo "$KEY" > /home/runner/.ssh/id_rsa
        chmod 400 /home/runner/.ssh/id_rsa
    - name: Running Playbook
      run: |
        cat ~/.ssh/id_rsa
        ssh ubuntu@44.204.11.47 mkdir hola
        echo "$USER --- $PWD" 
