
name: Ansible deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
    - name: set ansible config secrets
      env:
        KEY: ${{ secrets.laptop-key.pem }}
      run: |
        echo "$KEY" > /home/runner/laptop-key.pem
        chmod 400 /home/runner/laptop-key.pem
    - name: Running Playbook
      run: |
        cat /home/runner/laptop-key.pem
        ssh -i /home/runner/laptop-key.pem ubuntu@44.204.11.47 mkdir hola
        echo "$USER --- $PWD" 
