
name: Ansible deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible -y
        ansible --version
    - name: set ansible config secrets
      env:
        KEY: ${{ secrets.Private_Key }}
      run: |
        python3 --version
        sudo service sshd start
        sudo mkdir /home/runner/.ssh/
        sudo echo "$KEY" > /home/runner/id_rsa
        sudo chmod 400 /home/runner/.ssh/id_rsa
    - name: Running Playbook
      run: |
        ssh -i /home/runner/.ssh/id_rsa ubuntu@54.196.162.155 mkdir hola
        
