
name: Ansible deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible -y
        ansible --version
    - name: Custom Command
      env: 
        KEY: ${{ secrets.Private_Key }}
      run: |
        echo $PWD 
        echo $USER
        sudo mkdir /home/$USER/.ssh
        sudo echo $KEY
        sudo service sshd restart
        sudo chown -R $USER:$USER /home/$USER/.ssh
        git clone https://SAIKATDASGIT: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@github.com/SAIKATDASGIT/github-action.git
        ls -al /home/runner/work/github-action/github-action
        cp /home/runner/work/github-action/github-action /home/$USER
        sudo echo "$KEY" > /home/runner/.ssh/id_rsa
        sudo chmod 600 /home/runner/.ssh/id_rsa
    - name: Running Playbook
      run: |
        #ssh -i /home/runner/.ssh/id_rsa ubuntu@54.196.162.155 mkdir hola
        
