
name: Ansible deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible -y
        ansible --version
    - name: Custom Command
      env: 
        MY_KEY: ${{ secrets.PRIVATE }}
      run: |
        echo $PWD 
        echo $USER
        sudo service sshd start
        mkdir /home/$USER/.ssh
        echo "$MY_KEY" > /home/$USER/.ssh/id_rsa      
        sudo chmod 644 /home/$USER/.ssh/id_rsa
        sudo service sshd restart
        ls -al /home/$USER/.ssh
    - name: Connecting Other Server
      run: |
       ssh -i home/$USER/.ssh/id_rsa -o StrictHostKeyChecking=false ubuntu@3.85.61.248
       ansible -i ./inventory worker -m ping
        
