
name: Ansible deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible sshpass -y
        ansible --version
    - name: Custom Command
      #env: 
        #KEY: ${{ secrets.Private_Key }}
      run: |
        echo $PWD 
        echo $USER
        #sudo mkdir /home/$USER/.ssh
        #sudo echo $KEY
        sudo service sshd start
        #sudo chown -R $USER:$USER /home/$USER/.ssh
        git clone https://SAIKATDASGIT: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@github.com/SAIKATDASGIT/github-action.git
        cp -r /home/runner/work/github-action/github-action /home/$USER/         
        #cp /home/runner/github-action/id_rsa /home/runner/.ssh/id_rsa
        sudo chmod 600 /home/runner/github-action/id_rsa
        ls -al /home/$USER
    - name: Running Playbook
      run: |
       ls -al /home/runner/github-action
       ssh -i /home/runner/github-action/id_rsa ubuntu@34.205.141.106 ls
        
