
name: Ansible deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible sshpass -y
        ansible --version
    - name: Custom Command
      env: 
        MY_KEY: ${{ secrets.KEY }}
      run: |
        echo $PWD 
        echo $USER
        sudo service sshd start
        sudo echo "$MY_KEY" > /home/$USER/.ssh/id_rsa
        sudo chown -R $USER:$USER /home/$USER/.ssh
        git clone https://SAIKATDASGIT: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@github.com/SAIKATDASGIT/github-action.git
        cp -r /home/runner/work/github-action/github-action /home/$USER/         
        sudo chmod -r 600 /home/$USER/.ssh/
        ls -al /home/$USER/
    - name: Running Playbook
      run: |
       ssh -i /home/$USER/.ssh/id_rsa -o "StrictHostKeyChecking no" ubuntu@34.205.141.106 ls
        
